### ISSUE TITLE
Mypy Type Error due to Recent Changes to Litestar Middleware 

### ISSUE THREAD

**Issue by Faolain** [cofin/litestar-fullstack#43]
New issue has surface due to the new changes to the litestar exception middleware handling that has been merged in https://github.com/litestar-org/litestar/commit/88284016e3467d0f07f612ab4ac279e14ab96ca8 here leading to a mypy failure on pre-commit

<img width="872" alt="Screenshot 2023-08-06 at 11 12 41 PM" src="https://github.com/cofin/litestar-fullstack/assets/9613083/4b4e4ad8-bc36-4891-9612-ae73e9b149e7">

Issue on Line 120 where `create_exception_response` is expecting two arguments, with the first one being of type `Request[Any, Any, Any]` and the second being an exception. However, in the previous version only the exception is being passed. 

<img width="632" alt="Screenshot 2023-08-06 at 11 14 07 PM" src="https://github.com/cofin/litestar-fullstack/assets/9613083/c3e3da60-67b2-4058-a2ab-50ec47f8f4b7">

Reference new middleware implementation from litestar:
<img width="1370" alt="Screenshot 2023-08-06 at 11 24 01 PM" src="https://github.com/cofin/litestar-fullstack/assets/9613083/1b5a524d-080c-4acd-8b0d-cebbdaf0f326">

**Comment by cofin** [comment]
resolved by #44
